apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHZxbnVmZW5j
  CLOUDINARY_KEY: OTY5NDk5ODQ5Nzg3OTQ5
  CLOUDINARY_SECRET: VUxZSloxaHBwRXd3Y09HVktrOG1pRW1NVWFn
  MAPBOX_TOKEN: cGsuZXlKMUlqb2laMjl3YVdKeVlXaHRZV2xoYUNJc0ltRWlPaUpqYldsaVpuTXhhbm93ZFhZMU1tbHpZVEJ0WkRVM2FtRmhJbjAuSXVnSGctN2ttZVNScklCcWlZNDlwdw==
  DB_URL: bW9uZ29kYitzcnY6Ly9nb3BpZG9udGh1bGE1NjNfZGJfdXNlcjpPN25RSWFYRk9GemxCTVhpQGNsdXN0ZXIxLnpjaXNjY2cubW9uZ29kYi5uZXQvP2FwcE5hbWU9Q2x1c3RlcjE=
  SECRET: bXVzdGFmYQ==
